### ISSUE TITLE
Crash when opening Mods menu with Forge 41.0.94

### ISSUE THREAD

**Issue by Gamemassa** [MrCrayfish/Catalogue#35]
Minecraft version: 1.19
Forge version: 41.0.94
Catalogue version: 1.6.2

I can get to the main menu with no issues, but when I try to open the Mods menu, my whole screen goes red for a second (except the box on the left side where the mod list and scroll bar would be) and then my game crashes and I get the following error message:

-- Head --
Thread: Render thread
Stacktrace:
	at com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.lambda$loadAndCacheIcon$17(CatalogueModListScreen.java:597) ~[catalogue-1.6.2-1.19.jar%23154!/:1.6.2-1.19] {re:classloading,pl:epic_rei_lmao:B}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.loadAndCacheIcon(CatalogueModListScreen.java:586) ~[catalogue-1.6.2-1.19.jar%23154!/:1.6.2-1.19] {re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen$ModEntry.m_6311_(CatalogueModListScreen.java:736) ~[catalogue-1.6.2-1.19.jar%23154!/:1.6.2-1.19] {re:classloading,pl:epic_rei_lmao:B}
	at net.minecraft.client.gui.components.AbstractSelectionList.m_93451_(AbstractSelectionList.java:466) ~[client-1.19-20220607.102129-srg.jar%23194!/:?] {re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,xf:fml:configured:set_background_texture_1,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.components.AbstractSelectionList.m_6305_(AbstractSelectionList.java:201) ~[client-1.19-20220607.102129-srg.jar%23194!/:?] {re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,xf:fml:configured:set_background_texture_1,pl:runtimedistcleaner:A}
	at com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen$ModList.m_6305_(CatalogueModListScreen.java:688) ~[catalogue-1.6.2-1.19.jar%23154!/:1.6.2-1.19] {re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.drawModList(CatalogueModListScreen.java:274) ~[catalogue-1.6.2-1.19.jar%23154!/:1.6.2-1.19] {re:classloading,pl:epic_rei_lmao:B}
	at com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.m_6305_(CatalogueModListScreen.java:192) ~[catalogue-1.6.2-1.19.jar%23154!/:1.6.2-1.19] {re:classloading,pl:epic_rei_lmao:B}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:435) ~[forge-1.19-41.0.94-universal.jar%23199!/:?] {re:classloading,pl:epic_rei_lmao:B}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:428) ~[forge-1.19-41.0.94-universal.jar%23199!/:?] {re:classloading,pl:epic_rei_lmao:B}
-- Screen render details --
Details:
	Screen name: com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen
	Mouse location: Scaled: (253, 195). Absolute: (761.000000, 585.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19-20220607.102129-srg.jar%23194!/:?] {re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1084) ~[client-1.19-20220607.102129-srg.jar%23194!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:669) ~[client-1.19-20220607.102129-srg.jar%23194!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:epic_rei_lmao:B,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:byg_forge.mixins.json:client.MixinMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:206) ~[client-1.19-20220607.102129-srg.jar%23194!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.94.jar%2393!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2381!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

[crash-2022-07-12_08.26.30-client.txt](https://github.com/MrCrayfish/Catalogue/files/9092796/crash-2022-07-12_08.26.30-client.txt)

**Comment by MrCrayfish** [comment]
Fixed in 1.6.3
