### ISSUE TITLE
Invalid ID for itemIcon will crash the game.

### ISSUE THREAD

**Issue by Darkhax** [MrCrayfish/Catalogue#4]
When specifying an invalid item ID such as `"${modItemIcon"` the mod will crash trying to create the ResourceLocation. 

```
MC 1.15.5
Catalogue 1.1.0
Forge 36.1.16
```

```
Caused by: net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: minecraft:${modItemIcon}
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[forge-1.16.5-36.1.16_mapped_official_1.16.5-recomp.jar:?] {re:classloading}
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:38) ~[forge-1.16.5-36.1.16_mapped_official_1.16.5-recomp.jar:?] {re:classloading}
	at com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen$ModEntry.render(CatalogueModListScreen.java:589) ~[catalogue-459701-3285353_mapped_official_1.16.5.jar:1.1.0-1.16.5] {re:classloading}
	at net.minecraft.client.gui.widget.list.AbstractList.renderList(AbstractList.java:451) ~[forge-1.16.5-36.1.16_mapped_official_1.16.5-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.widget.list.AbstractList.render(AbstractList.java:190) ~[forge-1.16.5-36.1.16_mapped_official_1.16.5-recomp.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen$ModList.render(CatalogueModListScreen.java:551) ~[catalogue-459701-3285353_mapped_official_1.16.5.jar:1.1.0-1.16.5] {re:classloading}
	at com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.drawModList(CatalogueModListScreen.java:237) ~[catalogue-459701-3285353_mapped_official_1.16.5.jar:1.1.0-1.16.5] {re:classloading}
	at com.mrcrayfish.catalogue.client.screen.CatalogueModListScreen.render(CatalogueModListScreen.java:175) ~[catalogue-459701-3285353_mapped_official_1.16.5.jar:1.1.0-1.16.5] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:299) ~[forge-1.16.5-36.1.16_mapped_official_1.16.5-recomp.jar:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:492) ~[forge-1.16.5-36.1.16_mapped_official_1.16.5-recomp.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	... 14 more
```

**Comment by MrCrayfish** [comment]
Fixed in 57ac257f8a886b352337e7afdb953e6e1f6b90c5. Thanks for report
